server:
  port: 8090

api:
  key:
    authentication: test_api_key

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: adminadmin
      database: TechNews-dev
      port: 27017
      host: localhost
  application:
    name: TechNews_Backend

