server:
  port: 8090

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: adminadmin
      database: TechNews-dev
      port: 27017
      host: localhost